=== andywag/Simplifide/com.simplifide.core/schema/projectStructure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.simplifide.com/projectStructure" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns="http://www.simplifide.com/projectStructure">
    <xs:element name="basedir">
    	<xs:annotation>
    		<xs:documentation>
    			Main Class for the schema
    		</xs:documentation>
    	</xs:annotation>
    	<xs:complexType>
    		<xs:sequence maxOccurs="unbounded" minOccurs="0">
    			<xs:choice>
    				<xs:element ref="dir"></xs:element>
    				<xs:element ref="file"></xs:element>
    			</xs:choice>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>

    <xs:element name="dir">
        <xs:annotation>
        	<xs:documentation>Link to the simplifide distribution</xs:documentation>
        </xs:annotation>
        <xs:complexType>
        	<xs:sequence maxOccurs="unbounded" minOccurs="0">
        		<xs:choice>
        			<xs:element ref="dir"></xs:element>
        			<xs:element ref="file"></xs:element>
        		</xs:choice>
        	</xs:sequence>
        	<xs:attribute name="name" type="xs:string"></xs:attribute>
        	<xs:attribute name="link">
        		<xs:simpleType>
        			<xs:restriction base="xs:string">
        				<xs:enumeration value="design"></xs:enumeration>
        				<xs:enumeration value="projects"></xs:enumeration>
        				<xs:enumeration value="libraries"></xs:enumeration>
        				<xs:enumeration value="script"></xs:enumeration>
        				<xs:enumeration value="docs"></xs:enumeration>
        				<xs:enumeration value="test"></xs:enumeration>
        				<xs:enumeration value="build"></xs:enumeration>
        				<xs:enumeration value="synthesis"></xs:enumeration>
        				<xs:enumeration value="subprojects"></xs:enumeration>
        			</xs:restriction>
        		</xs:simpleType>
        	</xs:attribute>
        	<xs:attribute name="elink" type="xs:string"
        		use="optional">
        		<xs:annotation>
        			<xs:documentation>
        				Location of eclipse style link
        			</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="dlink" type="xs:string"></xs:attribute>
        	<xs:attribute name="copy" type="xs:string">
        		<xs:annotation>
        			<xs:documentation>Location where files should be copied from </xs:documentation>
        		</xs:annotation></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="file">
    	<xs:complexType>
    		<xs:attribute name="name" type="xs:string"></xs:attribute>
    	</xs:complexType>
    </xs:element>

  
    <xs:element name="suite">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="basedir"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>

    <xs:element name="project">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="basedir"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>

    <xs:element name="library">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="basedir"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>

    <xs:element name="subproject">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element ref="basedir"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>

    <xs:element name="root">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:choice maxOccurs="unbounded" minOccurs="1">
    				<xs:element ref="suite"></xs:element>
    				<xs:element ref="project"></xs:element>
    				<xs:element ref="library"></xs:element>
    				<xs:element ref="subproject"></xs:element>
    			</xs:choice>

    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
</xs:schema>

=== andywag/Simplifide/com.simplifide.core/resources/xilinx_example/Virtex_6/Structure.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="http://www.simplifide.com/projectStructure" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.simplifide.com/projectStructure projectStructure.xsd "> 
 	<suite>
 		<basedir>
 			<dir name="Documents" link="docs"/>
			<dir name="Projects" link="projects"/>
			<dir name="Libraries" link="libraries">
				<dir name="pcores" link="libraries"/></dir>
			<dir name="ZipFiles"></dir>
			<dir name="Scripts" link="script"></dir>
 		</basedir>
 	</suite>
 	<project>
 		<basedir>
 			<dir name="Documents" link="docs"/>
			<dir name="Ise" link="synthesis" />
			<dir name="Simscripts" link="test" />
			<dir name="Simulation" link="build" ></dir>
			<dir name="Synthesis"/>
			<dir name="Ucf"/>
			<dir name="Vhdl" link="design"></dir>
			<dir name="ZipFiles"/>
			<dir name="Libraries" link="subprojects">
				<dir name="pcores"/>
			</dir>
 		</basedir>
 	</project>
 	<library>
 		<basedir>
 			<dir name="Documents" link="docs"/>
			<dir name="Ise" link="synthesis" />
			<dir name="Simscripts" link="test" />
			<dir name="Simulation" link="build" ></dir>
			<dir name="Synthesis"/>
			<dir name="Ucf"/>
			<dir name="Vhdl" link="design"/>
			<dir name="ZipFiles"></dir>
 		</basedir>
 	</library>
 	<subproject>
 		<basedir>
 			<dir name="Documents" link="docs"/>
			<dir name="Ise" link="synthesis" />
			<dir name="Simscripts" link="test" />
			<dir name="Simulation" link="build" ></dir>
			<dir name="Synthesis"/>
			<dir name="Ucf"/>
			<dir name="Vhdl" link="design"/>
			<dir name="ZipFiles"></dir>
 		</basedir>
 	</subproject>
 	
</root>
